# Generated by Django 5.0 on 2024-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationModel',
            fields=[
                ('name', models.CharField(default='NULL', max_length=50)),
                ('roll_no', models.CharField(default='NULL', max_length=50, unique=True)),
                ('password', models.CharField(default='NULL', max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
