# Generated by Django 5.0 on 2025-01-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='roll_no',
        ),
    ]
