# Generated by Django 4.2.7 on 2023-12-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='name',
            field=models.CharField(default='NULL', max_length=50, primary_key=True, serialize=False),
        ),
    ]
