# Generated by Django 5.0 on 2025-02-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_remove_registrationmodel_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_message', models.JSONField()),
                ('user_message', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrationapp.registrationmodel')),
            ],
        ),
    ]
