# Generated by Django 4.2.7 on 2023-12-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_remove_registrationmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='roll_no',
            field=models.CharField(default='NULL', max_length=50, primary_key=True, serialize=False),
        ),
    ]
