# Generated by Django 4.2.7 on 2023-12-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0003_alter_registrationmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='email',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
