# Generated by Django 5.0 on 2023-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrationapp", "0005_alter_registrationmodel_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationmodel",
            name="email",
            field=models.CharField(default="NULL", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="registrationmodel",
            name="roll_no",
            field=models.CharField(
                default="NULL", max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
