# Generated by Django 5.0.13 on 2025-03-25 18:29

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=50)),
                ('password', models.CharField(default='NULL', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='messageModel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_message', models.JSONField()),
                ('user_message', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbotApp.registrationmodel')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
